### ISSUE TITLE
Find stripe size for low k values to avoid "strike size too large error"

### ISSUE THREAD

**Issue by SkycoinSynth** [watercompany/chiapos#10]
```
./ProofOfSpace -k 18 -f "plot.dat" create
operation: create
Generating plot for k=18 filename=plot.dat id=022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e

Caught exception: Stripe size too large
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted (core dumped)
```
The default stripe size is  65536 

```
./ProofOfSpace -k 18 -s 65536 -f "plot.dat" create
```

Will fail with 

```
Caught exception: Stripe size too large
```

For k=4, k=10, k=15, k=20

Run 

```
./ProofOfSpace -k 18 -s 65536 -f "plot.dat" create
```

With stripe size, reducing stripe size by a factor of 2, until you find a stripe size that works

2^0 = 1
2^1 = 2
2^2 = 4
2^3 = 8
2^4 = 16
2^5 = 32
2^6 = 64
2^7 = 128
2^8 = 256
2^9 = 512
2^10 = 1024
2^11 = 2048
2^12 = 4096
2^13 = 8192
2^14 = 16384
2^15 = 32768
2^16 = 65536

etc

1> Document in readme.md for k=4, k=10, k=15, k=20, the maximum power of 2 stripe size that can be used without an error

Maybe even check with a computer program the maximum power of 2 stripe size value for k=1 to k=21

2> Read the stripe -s value and the -k value in CLI
- if -s value is not set, automatically set the -s value based upon the k-value so that we do not get the "Stripe size too large" error

**Comment by Sameeranjoshi** [comment]
So for a command 
`./ProofOfSpace -k 21 -s <mentioned below>  -f "plot.dat" create`

When strip = 1024 things fail as mentioned above.
But for `2048` it passes.

So IIUC, you need such table for `For k=4, k=10, k=15, k=20`?
Please confirm

**Comment by SkycoinSynth** [comment]
> See this [code](https://github.com/watercompany/chiapos/blob/e03fa56ced6c00bf2f50342be5fe5ef3c20ed58a/src/pos_constants.hpp#L28)
> Values of k from 4 till 16 are invalid.
> Please reevaluate requirements, or should I change k's min value in code @SkycoinSynth ?

Yes. If 4 to 16 are invalid, then start at k=17.

If k < 17, then print error at start.

**Comment by Sameeranjoshi** [comment]
I get something like this 
```
command : ./ProofOfSpace -f "plot.dat" create -k 18 -s 2048 > /dev/null 2>&1
  k=18 s=2048
command : ./ProofOfSpace -f "plot.dat" create -k 19 -s 1024 > /dev/null 2>&1
  k=19 s=1024
command : ./ProofOfSpace -f "plot.dat" create -k 20 -s 2048 > /dev/null 2>&1
  k=20 s=2048
```
Now I have a script and I am gonna push it, do you need result for more k values @SkycoinSynth ?

**Comment by Sameeranjoshi** [comment]
For this 
```
2> Read the stripe -s value and the -k value in CLI

if -s value is not set, automatically set the -s value based upon the k-value so that we do not get the "Stripe size too large" error
```
We would need a map of working values.
It's seems to many values, do you want me to precompute such a map and use it @SkycoinSynth ?

**Comment by SkycoinSynth** [comment]
Yes. Precompute.

**Comment by Sameeranjoshi** [comment]
Precomputing using the script is taking crazy amount of time, I have very small power machine.
Is it possible to try on server, can you try/run the script?
If the issue of glibc was solved maybe if you provide me details on how to run things on server I can fire the script to get results.
