### ISSUE TITLE
make doesn't work after recent merges.

### ISSUE THREAD

**Issue by Sameeranjoshi** [watercompany/chiapos#25]
```
-- cxxopts version 2.2.0
-- Configuring done
CMake Error at CMakeLists.txt:51 (add_library):
  Cannot find source file:

chiapos/lib/FiniteStateEntropy/lib/fse_compress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CMakeLists.txt:51 (add_library):
  No SOURCES given to target: fse


CMake Generate step failed.  Build files cannot be regenerated correctly.
Makefile:718: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```

**Comment by SkycoinSynth** [comment]
Can you regress this. And find out which commit they broke this at.

Try "rm -rf ./build"

**Comment by SkycoinSynth** [comment]
Immediately

/home/cx/repo/chiapos/src/encoding.hpp:25:10: fatal error: ../lib/FiniteStateEntropy/lib/fse.h: No such file or directory
   25 | #include "../lib/FiniteStateEntropy/lib/fse.h"
  
Delete fse.h and these files from cmake and compilation and build. They are not used so I deleted them.

**Comment by Sameeranjoshi** [comment]
I think fse has dependencies on other files.
e.g entropy.{h,cpp} ones.
Because they have various class which are used inside the file and either need to figure out to remove these classes.
But IIUC you are sure you need to remove the `./lib/FiniteStateEntropy/lib/` folder? removing other folders like `visualstudio` and all is fine, but I was worried about `lib` folder.

I even tried to keep only the files which are mentioned in Cmake but then the dependencies go on increasing.

**Comment by Sameeranjoshi** [comment]
It started when you removed the FSE library files.
The Cmake needs these files, see cmake[ code here.](https://github.com/watercompany/chiapos/blob/83870b0c7f9ae5452aac76142faa5eddf19a4819/CMakeLists.txt#L35)
`chiapos/lib/FiniteStateEntropy/lib/fse_compress.c`

But then removing these files causes the issues which you mentioned after this PR.
Ok let me see.

**Comment by Sameeranjoshi** [comment]
#26

**Comment by Sameeranjoshi** [comment]
I see 
https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version
fails now.
For other build issues PR's pending.

**Comment by Sameeranjoshi** [comment]
Seems it build now.
This can be closed?
Can someone verify ?
