### ISSUE TITLE
Make Executable "Prover" for just proof checking, proof verification, challenges

### ISSUE THREAD

**Issue by SkycoinSynth** [watercompany/chiapos#33]
Make Executable "Prover" for just proof checking, proof verification, challenges

Put it in its own folder.

Only import the very minimum needed for this to function.

This is an executable for the "proof"., challenge, difficulty, proof verification related parts of "ProofOfSpace" , but with the -k generation functionality and other functionality removed.

**Comment by Sameeranjoshi** [comment]
#36

**Comment by Sameeranjoshi** [comment]
Close this.

**Comment by Sameeranjoshi** [comment]
Close this
