### ISSUE TITLE
Compilation: Add compilation option for linking against older version of glibc for ubuntu xenial

### ISSUE THREAD

**Issue by SkycoinSynth** [watercompany/chiapos#7]
Running the program compiled on Ubuntu 20, on Ubuntu xenial results in the following

```
./ProofOfSpace: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./ProofOfSpace)

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

On ubuntu xexial, the version of glibc is 2.23

```
ldd --version ldd
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23
```

We need to be able to compile the executable against this glibc version. Or to package a higher glibc version with the executable, so it can run on this older system.

**Comment by Sameeranjoshi** [comment]
How about 
`sudo apt-get install libstdc++6` ?

**Comment by SkycoinSynth** [comment]
> How about
> `sudo apt-get install libstdc++6` ?
> https://stackoverflow.com/a/29263413/9917291
> 
> or something like `sudo apt-get install --only-upgrade libstdc++6`

Yes. Add to readme in documentation on dependencies.

Document all dependencies at top with apt-get install command examples.

**Comment by SkycoinSynth** [comment]
> How about static build they should work everywhere @SkycoinSynth ?

Yes. There are several tickets for producing static builds.
- libc static build
- musl static build
- use of older glibc version for compilation/linking

**Comment by Sameeranjoshi** [comment]
I see following approaches:
1. Build glibc's version which is on xenial on native machine and then link it statically with the same, I think this is the approach I will try now.

**Comment by Sameeranjoshi** [comment]
Currently working, issue with static build, that needs resolution first.

**Comment by Sameeranjoshi** [comment]
Fix available for review.
